export type AllowabilityAnswer = "allowable" | "unallowable" | "conditionally_allowable";

export interface AllowabilityScenario {
  id: string;
  description: string;
  costCategory: string;
  amount: number;
  context: string;
  answer: AllowabilityAnswer;
  citation: string;
  explanation: string;
}

export const ALLOWABILITY_SCENARIOS: AllowabilityScenario[] = [
  { id: "a01", description: "Executive bonus tied to company-wide profitability", costCategory: "Compensation", amount: 45000, context: "CEO bonus for FY24, not tied to contract performance.", answer: "conditionally_allowable", citation: "FAR 31.205-6(p)", explanation: "Bonuses are allowable if reasonable and based on a written policy applied consistently. Must not exceed statutory caps for covered executives." },
  { id: "a02", description: "Client dinner at steakhouse for relationship building", costCategory: "Entertainment", amount: 850, context: "Charged to cost-reimbursement contract.", answer: "unallowable", citation: "FAR 31.205-14", explanation: "Entertainment costs are unallowable regardless of business purpose." },
  { id: "a03", description: "Commercial airfare coach class for site visit", costCategory: "Travel", amount: 420, context: "Employee travel per company policy aligned with JTR.", answer: "allowable", citation: "FAR 31.205-46(a)", explanation: "Travel costs are allowable when necessary and follow company policy consistent with JTR." },
  { id: "a04", description: "First-class upgrade on 4-hour flight", costCategory: "Travel", amount: 1200, context: "No medical or security justification documented.", answer: "unallowable", citation: "FAR 31.205-46(a)(2)", explanation: "First-class travel is unallowable unless specifically authorized or justified." },
  { id: "a05", description: "Parking fine at government facility", costCategory: "Fines", amount: 75, context: "Employee parked in unauthorized zone during contract work.", answer: "unallowable", citation: "FAR 31.205-15", explanation: "Fines and penalties from violations of law are unallowable." },
  { id: "a06", description: "Annual software license for accounting system", costCategory: "Depreciation/Software", amount: 12000, context: "Used exclusively on government cost-reimbursement contracts.", answer: "allowable", citation: "FAR 31.205-26", explanation: "Software costs necessary for contract performance are allowable when properly allocated." },
  { id: "a07", description: "Lobbying Congress for increased IT budget", costCategory: "Lobbying", amount: 25000, context: "Industry association dues portion attributable to lobbying.", answer: "unallowable", citation: "FAR 31.205-22", explanation: "Lobbying and political activity costs are unallowable." },
  { id: "a08", description: "DCAA audit support consultant fees", costCategory: "Professional services", amount: 8000, context: "Assisting with incurred cost audit for government contracts.", answer: "allowable", citation: "FAR 31.205-33", explanation: "Professional services necessary for contract compliance and audit response are allowable." },
  { id: "a09", description: "Holiday party for entire company", costCategory: "Entertainment", amount: 15000, context: "20% of attendees work on government contracts.", answer: "unallowable", citation: "FAR 31.205-14", explanation: "Entertainment is unallowable; no allocation makes holiday parties allowable." },
  { id: "a10", description: "Contingency fee paid to recruiter", costCategory: "Recruitment", amount: 18000, context: "Fee for hiring program manager on DoD contract.", answer: "conditionally_allowable", citation: "FAR 31.205-34", explanation: "Recruitment fees are allowable if reasonable and not based on a percentage of first-year salary in excess of limits." },
  { id: "a11", description: "Employee morale t-shirts with company logo", costCategory: "Employee morale", amount: 600, context: "Team building event for contract staff.", answer: "conditionally_allowable", citation: "FAR 31.205-13", explanation: "Minor morale items may be allowable if reasonable; excessive gifts are not." },
  { id: "a12", description: "Interest on line of credit for operations", costCategory: "Interest", amount: 3200, context: "General corporate borrowing, no specific asset.", answer: "unallowable", citation: "FAR 31.205-20", explanation: "Interest expense is generally unallowable except for facilities capital or pre-contract costs per specific rules." },
  { id: "a13", description: "Bad debt write-off from bankrupt subcontractor", costCategory: "Bad debts", amount: 45000, context: "Subcontractor on government prime contract defaulted.", answer: "unallowable", citation: "FAR 31.205-3", explanation: "Bad debts are unallowable except under specific agency regulations." },
  { id: "a14", description: "Legal fees for contract dispute with agency", costCategory: "Legal", amount: 22000, context: "Defending equitable adjustment claim.", answer: "allowable", citation: "FAR 31.205-47", explanation: "Legal costs for contract-related proceedings are allowable when approved or necessary." },
  { id: "a15", description: "Legal fees for patent infringement unrelated to contract", costCategory: "Legal", amount: 35000, context: "Commercial product line not on government work.", answer: "unallowable", citation: "FAR 31.205-47(b)", explanation: "Patent defense unrelated to contract performance is unallowable." },
  { id: "a16", description: "Office supplies allocated via CAS pool", costCategory: "Material", amount: 450, context: "Standard supplies used on contract floor.", answer: "allowable", citation: "FAR 31.205-26", explanation: "Material costs necessary for performance are allowable when properly allocated." },
  { id: "a17", description: "Donation to local charity gala table", costCategory: "Contributions", amount: 5000, context: "Sponsorship charged to G&A pool.", answer: "unallowable", citation: "FAR 31.205-8", explanation: "Contributions and donations are unallowable." },
  { id: "a18", description: "Workers compensation insurance premium", costCategory: "Insurance", amount: 8900, context: "Required by state law for all employees.", answer: "allowable", citation: "FAR 31.205-19", explanation: "Insurance required by law or contract is allowable." },
  { id: "a19", description: "Life insurance on executive paid by company", costCategory: "Insurance", amount: 4200, context: "Key-person policy benefiting executive's estate.", answer: "unallowable", citation: "FAR 31.205-19(c)", explanation: "Life insurance benefiting owners or beneficiaries beyond business need is unallowable." },
  { id: "a20", description: "Training course on FAR Part 15 for capture staff", costCategory: "Training", amount: 1800, context: "Directly improves proposal quality on current contracts.", answer: "allowable", citation: "FAR 31.205-48", explanation: "Training necessary for current job duties is allowable." },
  { id: "a21", description: "MBA tuition reimbursement for marketing director", costCategory: "Training", amount: 15000, context: "Degree not required for current role on government work.", answer: "unallowable", citation: "FAR 31.205-48(d)", explanation: "Training leading to a degree or unrelated to current duties is unallowable." },
  { id: "a22", description: "Depreciation on laptop used 100% on contract", costCategory: "Depreciation", amount: 900, context: "Capitalized per GAAP, 3-year life.", answer: "allowable", citation: "FAR 31.205-13", explanation: "Depreciation on assets used in contract performance is allowable per GAAP." },
  { id: "a23", description: "Accelerated depreciation on office furniture", costCategory: "Depreciation", amount: 4500, context: "200% declining balance vs. straight-line.", answer: "conditionally_allowable", citation: "FAR 31.205-13(b)", explanation: "Depreciation must follow GAAP; accelerated methods may be challenged if unreasonable." },
  { id: "a24", description: "Alcoholic beverages at company picnic", costCategory: "Entertainment", amount: 350, context: "50 employees, 10 on government contracts.", answer: "unallowable", citation: "FAR 31.205-14", explanation: "Entertainment including social events with alcohol is unallowable." },
  { id: "a25", description: "Overtime premium for contract engineers", costCategory: "Labor", amount: 5600, context: "Approved by CO for schedule-critical deliverable.", answer: "allowable", citation: "FAR 31.205-6", explanation: "Overtime is allowable when authorized and reasonable for contract needs." },
  { id: "a26", description: "Unapproved overtime on fixed-price contract", costCategory: "Labor", amount: 3200, context: "No mod; contractor absorbed on FFP.", answer: "unallowable", citation: "FAR 31.205-6", explanation: "On FFP, extra hours without consideration are the contractor's risk—not charged to other CR contracts." },
  { id: "a27", description: "Relocation costs for new hire on contract", costCategory: "Relocation", amount: 11000, context: "Per written company relocation policy.", answer: "allowable", citation: "FAR 31.205-35", explanation: "Relocation costs are allowable when pursuant to a formal policy and reasonable." },
  { id: "a28", description: "Stock option expense for executives", costCategory: "Compensation", amount: 85000, context: "Allocated through G&A to government contracts.", answer: "unallowable", citation: "FAR 31.205-6(p)(2)", explanation: "Costs for stock options and similar compensation are unallowable." },
  { id: "a29", description: "Bid and proposal costs on current pursuit", costCategory: "B&P", amount: 42000, context: "Proposal for cost-reimbursement contract.", answer: "allowable", citation: "FAR 31.205-18", explanation: "B&P for proposed cost-reimbursement contracts is allowable; for FFP typically not." },
  { id: "a30", description: "B&P costs on lost FFP competition", costCategory: "B&P", amount: 28000, context: "Competitive FFP award to competitor.", answer: "unallowable", citation: "FAR 31.205-18(a)(1)", explanation: "B&P for FFP contracts is unallowable except under specific conditions." },
  { id: "a31", description: "Independent research on AI tooling", costCategory: "IR&D", amount: 65000, context: "Not sponsored by government; potential future use.", answer: "conditionally_allowable", citation: "FAR 31.205-18", explanation: "IR&D may be allowable under specific criteria; must have potential relationship to business." },
  { id: "a32", description: "Trade association membership dues", costCategory: "Memberships", amount: 2400, context: "NDIA membership for BD team.", answer: "conditionally_allowable", citation: "FAR 31.205-40", explanation: "Allowable if related to business; lobbying portion must be excluded." },
  { id: "a33", description: "Flowers for employee bereavement", costCategory: "Employee morale", amount: 85, context: "Sent to family of contract analyst.", answer: "allowable", citation: "FAR 31.205-13", explanation: "Nominal morale gestures of this type are generally considered reasonable." },
  { id: "a34", description: "SEC fine for financial reporting violation", costCategory: "Fines", amount: 50000, context: "Corporate-level penalty.", answer: "unallowable", citation: "FAR 31.205-15", explanation: "All fines from violations of law are unallowable." },
  { id: "a35", description: "Cybersecurity tools for CMMC compliance", costCategory: "Material/Software", amount: 18000, context: "Required for DoD contract performance.", answer: "allowable", citation: "FAR 31.205-26", explanation: "Costs necessary to meet contract security requirements are allowable." },
  { id: "a36", description: "Personal use portion of company vehicle", costCategory: "Auto", amount: 2100, context: "Executive vehicle with undocumented personal miles.", answer: "unallowable", citation: "FAR 31.205-45", explanation: "Personal use of company assets must be excluded; unallowable portion." },
  { id: "a37", description: "Approved home office internet for remote worker", costCategory: "Communications", amount: 960, context: "100% allocated to government contract per telework policy.", answer: "allowable", citation: "FAR 31.205-46", explanation: "Communications costs for contract work are allowable when properly documented." },
  { id: "a38", description: "Golf outing with potential teaming partner", costCategory: "Entertainment", amount: 650, context: "Pre-award teaming discussion.", answer: "unallowable", citation: "FAR 31.205-14", explanation: "Entertainment remains unallowable even during business development." },
  { id: "a39", description: "DCAA-forward pricing audit support", costCategory: "Professional services", amount: 5500, context: "Preparing indirect rate proposal for DCMA.", answer: "allowable", citation: "FAR 31.205-33", explanation: "Professional services supporting allowable contract pricing are allowable." },
  { id: "a40", description: "Severance pay for laid-off staff", costCategory: "Compensation", amount: 32000, context: "Reduction in force after contract loss.", answer: "conditionally_allowable", citation: "FAR 31.205-6(b)(2)", explanation: "Severance may be allowable if pursuant to established policy and reasonable." },
  { id: "a41", description: "Office lease for contract performance site", costCategory: "Facilities", amount: 48000, context: "Dedicated floor for program team.", answer: "allowable", citation: "FAR 31.205-25", explanation: "Rental costs for facilities used in contract performance are allowable." },
  { id: "a42", description: "Commuting costs from home to primary office", costCategory: "Travel", amount: 1200, context: "Employee mileage reimbursement daily.", answer: "unallowable", citation: "FAR 31.205-46(b)", explanation: "Home-to-work commuting is unallowable." },
  { id: "a43", description: "Per diem meals on travel to client site", costCategory: "Travel", amount: 186, context: "3-day trip, GSA per diem rates.", answer: "allowable", citation: "FAR 31.205-46(a)(4)", explanation: "Meals on official travel at per diem or actual cost within limits are allowable." },
  { id: "a44", description: "Premium pay for hazardous duty at site", costCategory: "Labor", amount: 7800, context: "Documented hazard per contract PWS.", answer: "allowable", citation: "FAR 31.205-6", explanation: "Premium pay is allowable when required by contract and reasonable." },
  { id: "a45", description: "Costs of idle facilities during contract gap", costCategory: "Facilities", amount: 22000, context: "Two-month gap between task orders.", answer: "conditionally_allowable", citation: "FAR 31.205-17", explanation: "Idle facility costs may be allowable if reasonable and mitigated." },
  { id: "a46", description: "Advertising in trade magazine", costCategory: "Advertising", amount: 3500, context: "Promoting commercial product line only.", answer: "unallowable", citation: "FAR 31.205-1", explanation: "Advertising not directed at government sales is unallowable." },
  { id: "a47", description: "Advertising for SAM.gov capability statement", costCategory: "Advertising", amount: 800, context: "Promoting services sold to government.", answer: "allowable", citation: "FAR 31.205-1(b)", explanation: "Advertising specifically for government market may be allowable." },
  { id: "a48", description: "Employee physical exam required by contract", costCategory: "Health", amount: 450, context: "PWS requires annual fitness for duty exam.", answer: "allowable", citation: "FAR 31.205-6", explanation: "Medical exams required for contract performance are allowable." },
  { id: "a49", description: "General wellness program gym subsidy", costCategory: "Employee benefits", amount: 6000, context: "Company-wide benefit, allocated to G&A.", answer: "conditionally_allowable", citation: "FAR 31.205-6", explanation: "Fringe benefits are allowable if reasonable and pursuant to established policy." },
  { id: "a50", description: "Contractor purchase of government-furnished equipment", costCategory: "Material", amount: 0, context: "GFE provided at no cost; contractor tried to charge handling fee to indirect pool.", answer: "unallowable", citation: "FAR 31.205-26", explanation: "Cannot inflate costs for GFE; handling must be reasonable and authorized." },
];

export function getAllowabilityScenario(id: string): AllowabilityScenario | undefined {
  return ALLOWABILITY_SCENARIOS.find((s) => s.id === id);
}
