export interface FarClauseEntry {
  id: string;
  citation: string;
  title: string;
  part: number;
  plainEnglish: string;
  contractorImpact: string;
  governmentImpact: string;
  relatedClauses: string[];
  keywords: string[];
}

export const FAR_NAVIGATOR_CLAUSES: FarClauseEntry[] = [
  { id: "1-102", citation: "FAR 1.102", title: "Guiding principles", part: 1, plainEnglish: "The acquisition system must deliver best value, promote competition, and maintain public trust.", contractorImpact: "Proposals must map strengths to evaluation factors beyond price.", governmentImpact: "COs must document best-value tradeoffs when price is not lowest.", relatedClauses: ["FAR 15.101", "FAR 1.102-2"], keywords: ["best value", "competition", "integrity"] },
  { id: "1-602", citation: "FAR 1.602", title: "Contracting officer authority", part: 1, plainEnglish: "Only warranted contracting officers can bind the government.", contractorImpact: "Perform only on CO-signed modifications; COR direction is not binding.", governmentImpact: "Unauthorized commitments require ratification under 1.602-3.", relatedClauses: ["FAR 1.602-3", "FAR 1.604"], keywords: ["CO", "warrant", "authority"] },
  { id: "1-604", citation: "FAR 1.604", title: "COR appointment", part: 1, plainEnglish: "CORs monitor technical performance but cannot change contract terms.", contractorImpact: "Get scope changes in writing from the CO, not the COR.", governmentImpact: "Agencies must appoint CORs in writing with defined limits.", relatedClauses: ["FAR 1.602", "FAR 43.103"], keywords: ["COR", "technical direction"] },
  { id: "2-101", citation: "FAR 2.101", title: "Definitions", part: 2, plainEnglish: "Central dictionary for acquisition terms used throughout the FAR.", contractorImpact: "Misreading defined terms (e.g., commercial item) affects compliance.", governmentImpact: "COs apply these definitions in solicitations and awards.", relatedClauses: ["FAR 12.102", "FAR 15.001"], keywords: ["definitions", "commercial item"] },
  { id: "3-104", citation: "FAR 3.104", title: "Procurement integrity", part: 3, plainEnglish: "Protects source selection information and prohibits improper disclosure.", contractorImpact: "Do not seek or use competitor proposal information.", governmentImpact: "COs must control access to proposals and source selection docs.", relatedClauses: ["FAR 3.104-4", "FAR 52.203-10"], keywords: ["procurement integrity", "OCI"] },
  { id: "3-702", citation: "FAR 3.702", title: "Whistleblower protections", part: 3, plainEnglish: "Contractors cannot retaliate against employees reporting fraud.", contractorImpact: "Maintain ethics hotlines and document non-retaliation policies.", governmentImpact: "Agencies investigate reprisal complaints.", relatedClauses: ["FAR 52.203-17"], keywords: ["whistleblower", "ethics"] },
  { id: "4-801", citation: "FAR 4.801", title: "Contract files", part: 4, plainEnglish: "Government must maintain complete contract administration records.", contractorImpact: "Your correspondence becomes part of the official file.", governmentImpact: "Incomplete files weaken protest and audit defenses.", relatedClauses: ["FAR 4.803"], keywords: ["contract file", "records"] },
  { id: "5-003", citation: "FAR 5.003", title: "Synopsis requirements", part: 5, plainEnglish: "Most acquisitions over micro-purchase must be publicized.", contractorImpact: "Monitor SAM.gov for opportunities matching your NAICS.", governmentImpact: "Failure to synopsize can invalidate the procurement.", relatedClauses: ["FAR 5.201", "FAR 52.204-7"], keywords: ["synopsis", "SAM.gov"] },
  { id: "6-001", citation: "FAR 6.001", title: "Full and open competition", part: 6, plainEnglish: "Default rule: all responsible sources may compete.", contractorImpact: "Challenge unjustified sole-source or limited competitions.", governmentImpact: "Must justify exceptions under Part 6.", relatedClauses: ["FAR 6.302", "FAR 19.502"], keywords: ["competition", "sole source"] },
  { id: "6-302", citation: "FAR 6.302", title: "Exceptions to competition", part: 6, plainEnglish: "Lists statutory grounds for other than full and open competition.", contractorImpact: "Understand which exceptions incumbents exploit.", governmentImpact: "Must document J&A for each exception used.", relatedClauses: ["FAR 6.303", "FAR 19.504"], keywords: ["J&A", "sole source"] },
  { id: "7-104", citation: "FAR 7.104", title: "Acquisition planning", part: 7, plainEnglish: "Agencies plan acquisitions before releasing solicitations.", contractorImpact: "Early engagement during planning shapes requirements.", governmentImpact: "AP documents strategy, competition, and small business goals.", relatedClauses: ["FAR 7.105", "FAR 10.001"], keywords: ["acquisition plan", "planning"] },
  { id: "8-405", citation: "FAR 8.405", title: "Ordering procedures for schedules", part: 8, plainEnglish: "Rules for placing orders against GSA or agency schedules.", contractorImpact: "Schedule holders compete at order level, not just award.", governmentImpact: "COs follow fair opportunity procedures for orders.", relatedClauses: ["FAR 8.404", "FAR 16.505"], keywords: ["GSA schedule", "BPA"] },
  { id: "9-104", citation: "FAR 9.104", title: "Standards for responsibility", part: 9, plainEnglish: "Offerors must be responsible: capable, qualified, and ethical.", contractorImpact: "Maintain financial capacity, CPARS, and ethics compliance.", governmentImpact: "CO may find nonresponsible and refer to SBA certificate.", relatedClauses: ["FAR 9.105", "FAR 19.602"], keywords: ["responsibility", "CPARS"] },
  { id: "10-001", citation: "FAR 10.001", title: "Market research", part: 10, plainEnglish: "Agencies must understand industry before buying.", contractorImpact: "Respond to RFIs and sources sought to influence requirements.", governmentImpact: "Document market research to support commercial item determinations.", relatedClauses: ["FAR 12.102", "FAR 10.002"], keywords: ["market research", "RFI"] },
  { id: "11-002", citation: "FAR 11.002", title: "Describing agency needs", part: 11, plainEnglish: "Requirements must be stated clearly without unnecessary restrictions.", contractorImpact: "Protest overly restrictive specs that favor incumbents.", governmentImpact: "Must use performance specs when practicable.", relatedClauses: ["FAR 11.104", "FAR 12.202"], keywords: ["requirements", "specifications"] },
  { id: "12-102", citation: "FAR 12.102", title: "Commercial items", part: 12, plainEnglish: "Commercial products/services follow streamlined procedures.", contractorImpact: "Qualify offerings as commercial to reduce compliance burden.", governmentImpact: "Must determine commerciality before using Part 12.", relatedClauses: ["FAR 12.207", "FAR 52.212-4"], keywords: ["commercial item", "Part 12"] },
  { id: "12-207", citation: "FAR 12.207", title: "Contract type for commercial items", part: 12, plainEnglish: "Firm-fixed-price is preferred for commercial acquisitions.", contractorImpact: "Expect FFP terms and limited cost data requirements.", governmentImpact: "Must justify other than FFP for commercial items.", relatedClauses: ["FAR 16.103", "FAR 52.212-4"], keywords: ["FFP", "commercial"] },
  { id: "13-003", citation: "FAR 13.003", title: "Simplified acquisition threshold", part: 13, plainEnglish: "Streamlined procedures for purchases below SAT.", contractorImpact: "Small purchases may not require full proposals.", governmentImpact: "Micro-purchase and SAP rules apply by dollar level.", relatedClauses: ["FAR 13.106", "FAR 2.101"], keywords: ["SAT", "simplified"] },
  { id: "14-408", citation: "FAR 14.408", title: "Award of sealed bids", part: 14, plainEnglish: "Lowest responsive responsible bidder wins in sealed bidding.", contractorImpact: "Price is determinative; no discussions to fix mistakes.", governmentImpact: "Must reject nonresponsive bids.", relatedClauses: ["FAR 14.404", "FAR 52.214-16"], keywords: ["sealed bidding", "LPTA"] },
  { id: "15-306", citation: "FAR 15.306", title: "Exchanges with offerors", part: 15, plainEnglish: "Defines discussions, clarifications, and communications.", contractorImpact: "Do not assume all communications are equal—discussions allow revisions.", governmentImpact: "Must conduct fair and equal exchanges.", relatedClauses: ["FAR 15.307", "FAR 15.308"], keywords: ["discussions", "negotiation"] },
  { id: "15-308", citation: "FAR 15.308", title: "Source selection decision", part: 15, plainEnglish: "SSO must document rationale for award.", contractorImpact: "Debrief requests can reveal evaluation errors.", governmentImpact: "Documentation must support best-value decision.", relatedClauses: ["FAR 15.503", "FAR 15.504"], keywords: ["source selection", "SSO"] },
  { id: "15-403", citation: "FAR 15.403", title: "Cost or pricing data", part: 15, plainEnglish: "Certified cost/pricing data required above TINA threshold.", contractorImpact: "Submit accurate data; defective pricing creates liability.", governmentImpact: "Must obtain certificate when required.", relatedClauses: ["FAR 15.407", "FAR 52.215-10"], keywords: ["TINA", "cost data"] },
  { id: "15-404", citation: "FAR 15.404", title: "Proposal analysis techniques", part: 15, plainEnglish: "CO must perform price analysis and/or cost analysis.", contractorImpact: "Support proposed prices with market data or cost buildup.", governmentImpact: "Must document analysis technique used.", relatedClauses: ["FAR 15.403", "FAR 31.201"], keywords: ["price analysis", "cost analysis"] },
  { id: "16-103", citation: "FAR 16.103", title: "Fixed-price contracts", part: 16, plainEnglish: "Contractor bears cost risk; payment for delivered supplies/services.", contractorImpact: "Price carefully—overruns are your loss.", governmentImpact: "Use when requirements are definite.", relatedClauses: ["FAR 16.202", "FAR 52.216-7"], keywords: ["FFP", "fixed price"] },
  { id: "16-601", citation: "FAR 16.601", title: "Time-and-materials", part: 16, plainEnglish: "Payment based on labor hours and material costs.", contractorImpact: "Track hours meticulously; fee is limited.", governmentImpact: "Must establish ceiling price; T&M is last resort.", relatedClauses: ["FAR 16.601", "FAR 52.232-7"], keywords: ["T&M", "labor hours"] },
  { id: "16-505", citation: "FAR 16.505", title: "IDIQ ordering", part: 16, plainEnglish: "Rules for task/delivery orders under multiple-award contracts.", contractorImpact: "Compete for each order; past performance at order level matters.", governmentImpact: "Fair opportunity required unless exception applies.", relatedClauses: ["FAR 8.405", "FAR 19.504"], keywords: ["IDIQ", "task order"] },
  { id: "17-208", citation: "FAR 17.208", title: "Options", part: 17, plainEnglish: "Unilateral right to extend contract for additional periods.", contractorImpact: "Price options at award; performance during base period affects exercise.", governmentImpact: "Must evaluate option value in source selection.", relatedClauses: ["FAR 17.207", "FAR 52.217-8"], keywords: ["option", "extension"] },
  { id: "19-502", citation: "FAR 19.502", title: "Small business set-asides", part: 19, plainEnglish: "Acquisitions expected above $250K reserved for small business when two or more can compete.", contractorImpact: "Verify size status and NAICS for set-aside eligibility.", governmentImpact: "Must perform market research before full and open.", relatedClauses: ["FAR 19.503", "FAR 52.219-1"], keywords: ["set-aside", "small business"] },
  { id: "19-704", citation: "FAR 19.704", title: "Subcontracting plan contents", part: 19, plainEnglish: "Large businesses must propose small business subcontracting goals.", contractorImpact: "Meet goals or face liquidated damages and CPARS impact.", governmentImpact: "Must evaluate and monitor plan performance.", relatedClauses: ["FAR 52.219-9", "FAR 19.705"], keywords: ["subcontracting plan", "52.219-9"] },
  { id: "22-103", citation: "FAR 22.103", title: "Service Contract Act", part: 22, plainEnglish: "Service contracts over $2,500 require wage determinations.", contractorImpact: "Pay prevailing wages; SCA violations trigger back pay.", governmentImpact: "Must include applicable WD in solicitation.", relatedClauses: ["FAR 52.222-41", "FAR 22.1006"], keywords: ["SCA", "wage determination"] },
  { id: "31-201", citation: "FAR 31.201", title: "Cost principles general", part: 31, plainEnglish: "Costs must be reasonable, allocable, and conform to GAAP.", contractorImpact: "Every indirect and direct cost must pass the four-part test.", governmentImpact: "Auditors apply Part 31 in incurred cost audits.", relatedClauses: ["FAR 31.205", "FAR 52.215-2"], keywords: ["cost principles", "allowability"] },
  { id: "31-205", citation: "FAR 31.205", title: "Selected costs", part: 31, plainEnglish: "Specific allowability rules for individual cost categories.", contractorImpact: "Know which costs are unallowable (entertainment, fines, etc.).", governmentImpact: "DCAA applies these in audits and forward pricing.", relatedClauses: ["FAR 31.201", "FAR 52.216-7"], keywords: ["allowability", "31.205"] },
  { id: "31-205-6", citation: "FAR 31.205-6", title: "Compensation costs", part: 31, plainEnglish: "Rules for allowability of salaries, bonuses, and benefits.", contractorImpact: "Executive compensation capped; document reasonableness.", governmentImpact: "Reviews compensation against market benchmarks.", relatedClauses: ["FAR 31.205-13", "FAR 52.216-7"], keywords: ["compensation", "salary"] },
  { id: "31-205-13", citation: "FAR 31.205-13", title: "Depreciation", part: 31, plainEnglish: "Depreciation must follow GAAP and be reasonable.", contractorImpact: "Capitalize assets properly; do not accelerate unreasonably.", governmentImpact: "Auditors test useful life and salvage assumptions.", relatedClauses: ["FAR 31.205-26"], keywords: ["depreciation", "capital"] },
  { id: "31-205-26", citation: "FAR 31.205-26", title: "Material costs", part: 31, plainEnglish: "Material must be necessary, reasonably priced, and properly accounted.", contractorImpact: "Retain purchase records and competitive quotes.", governmentImpact: "Tests for reasonableness and allocability.", relatedClauses: ["FAR 31.205-33"], keywords: ["material", "procurement"] },
  { id: "31-205-33", citation: "FAR 31.205-33", title: "Professional services", part: 31, plainEnglish: "Legal, consulting, and professional fees must be reasonable and necessary.", contractorImpact: "Document scope and hourly rates for consultants.", governmentImpact: "May disallow excessive legal fees.", relatedClauses: ["FAR 31.205-34"], keywords: ["consulting", "legal fees"] },
  { id: "31-205-46", citation: "FAR 31.205-46", title: "Travel costs", part: 31, plainEnglish: "Travel must follow company policy and FAR/JTR limits.", contractorImpact: "Use per diem rates; no first-class without justification.", governmentImpact: "Auditors compare to JTR and company policy.", relatedClauses: ["FAR 31.205-51"], keywords: ["travel", "per diem"] },
  { id: "31-205-51", citation: "FAR 31.205-51", title: "Entertainment", part: 31, plainEnglish: "Entertainment costs are generally unallowable.", contractorImpact: "Never charge client dinners or tickets to government contracts.", governmentImpact: "Automatically disallowed in audits.", relatedClauses: ["FAR 31.205-14"], keywords: ["entertainment", "unallowable"] },
  { id: "32-702", citation: "FAR 32.702", title: "Progress payments", part: 32, plainEnglish: "Contractor receives periodic payments based on costs incurred.", contractorImpact: "Maintain adequate accounting system for progress payments.", governmentImpact: "Must protect government interest with liquidation rate.", relatedClauses: ["FAR 32.503", "FAR 52.232-16"], keywords: ["progress payments", "cash flow"] },
  { id: "42-1203", citation: "FAR 42.1203", title: "Novation agreements", part: 42, plainEnglish: "Transfer contract to successor when company is sold.", contractorImpact: "Novation required before performing after asset purchase.", governmentImpact: "CO must approve novation; no automatic transfer.", relatedClauses: ["FAR 42.1204", "FAR 52.249-1"], keywords: ["novation", "M&A"] },
  { id: "43-103", citation: "FAR 43.103", title: "Modification authority", part: 43, plainEnglish: "Only CO can modify contract scope, price, or schedule.", contractorImpact: "Do not perform out-of-scope work without bilateral mod.", governmentImpact: "Must document consideration for bilateral changes.", relatedClauses: ["FAR 43.101", "FAR 52.243-1"], keywords: ["modification", "scope creep"] },
  { id: "46-707", citation: "FAR 46.707", title: "Warranties", part: 46, plainEnglish: "Government may require warranties for supplies and services.", contractorImpact: "Warranty costs must be priced and performed.", governmentImpact: "Includes warranty clauses based on acquisition type.", relatedClauses: ["FAR 46.708", "FAR 52.246-4"], keywords: ["warranty", "quality"] },
  { id: "49-101", citation: "FAR 49.101", title: "Termination for convenience", part: 49, plainEnglish: "Government may end contract for convenience with settlement.", contractorImpact: "Submit termination settlement proposal promptly.", governmentImpact: "Must use T4C clause and follow Part 49 procedures.", relatedClauses: ["FAR 49.602", "FAR 52.249-2"], keywords: ["T4C", "termination"] },
  { id: "52-203-10", citation: "FAR 52.203-10", title: "Price or fee adjustment", part: 52, plainEnglish: "Contractor must disclose defective pricing.", contractorImpact: "Voluntary disclosure reduces penalties.", governmentImpact: "May recover overpayment plus interest.", relatedClauses: ["FAR 15.407", "FAR 3.104"], keywords: ["defective pricing", "disclosure"] },
  { id: "52-212-4", citation: "FAR 52.212-4", title: "Commercial items contract terms", part: 52, plainEnglish: "Standard terms for commercial item acquisitions.", contractorImpact: "Understand streamlined terms vs. full Part 52 stack.", governmentImpact: "Prescribed for commercial item contracts.", relatedClauses: ["FAR 12.301", "FAR 12.403"], keywords: ["commercial terms", "52.212-4"] },
  { id: "52-215-2", citation: "FAR 52.215-2", title: "Audit and records", part: 52, plainEnglish: "Government may audit cost-type and T&M contract records.", contractorImpact: "Retain records 3 years after final payment.", governmentImpact: "DCAA/DCMA access for audits.", relatedClauses: ["FAR 31.201", "FAR 52.216-7"], keywords: ["audit", "records retention"] },
  { id: "52-216-7", citation: "FAR 52.216-7", title: "Allowable cost and payment", part: 52, plainEnglish: "Incorporates FAR Part 31 into cost-reimbursement contracts.", contractorImpact: "All costs must be allowable under Part 31.", governmentImpact: "Basis for incurred cost audits.", relatedClauses: ["FAR 31.205", "FAR 52.215-2"], keywords: ["allowable cost", "Part 31"] },
  { id: "52-219-9", citation: "FAR 52.219-9", title: "Small business subcontracting plan", part: 52, plainEnglish: "Requires large prime to subcontract to small businesses.", contractorImpact: "Submit plan with offer; report quarterly.", governmentImpact: "Monitors achievement vs. goals.", relatedClauses: ["FAR 19.704", "FAR 19.705"], keywords: ["subcontracting", "small business"] },
  { id: "52-222-41", citation: "FAR 52.222-41", title: "Service Contract Act clause", part: 52, plainEnglish: "Requires compliance with wage determinations on service contracts.", contractorImpact: "Post WD at worksite; pay fringe benefits.", governmentImpact: "Enforced by DOL.", relatedClauses: ["FAR 22.103", "FAR 22.1006"], keywords: ["SCA", "wages"] },
  { id: "52-243-1", citation: "FAR 52.243-1", title: "Changes — Fixed price", part: 52, plainEnglish: "CO may order changes within general scope.", contractorImpact: "Submit equitable adjustment within timeframe.", governmentImpact: "Must be within scope of original contract.", relatedClauses: ["FAR 43.103", "FAR 52.243-2"], keywords: ["change order", "equitable adjustment"] },
  { id: "52-249-2", citation: "FAR 52.249-2", title: "Termination for convenience", part: 52, plainEnglish: "Standard clause allowing government to terminate.", contractorImpact: "Entitled to costs plus reasonable profit on work performed.", governmentImpact: "Must follow Part 49 settlement procedures.", relatedClauses: ["FAR 49.101", "FAR 49.602"], keywords: ["T4C", "settlement"] },
];

export function searchFarClauses(query: string): FarClauseEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return FAR_NAVIGATOR_CLAUSES;
  return FAR_NAVIGATOR_CLAUSES.filter(
    (c) =>
      c.citation.toLowerCase().includes(q) ||
      c.title.toLowerCase().includes(q) ||
      c.plainEnglish.toLowerCase().includes(q) ||
      c.keywords.some((k) => k.toLowerCase().includes(q))
  );
}

export function getFarClauseById(id: string): FarClauseEntry | undefined {
  return FAR_NAVIGATOR_CLAUSES.find((c) => c.id === id);
}
