import type { DayInLifeBlock } from "../types";

export const DAY_IN_LIFE_BLOCKS: DayInLifeBlock[] = [
  {
    id: "wawf-invoices",
    time: "8:00 AM",
    title: "Check WAWF for invoice status",
    teachPoints: [
      "Wide Area Workflow (WAWF) is the DoD-wide electronic invoicing and receipt/acceptance system — most defense contractors must submit invoices through it before payment.",
      "Each invoice ties to Contract Line Item Numbers (CLINs), requires a valid receiving report (DD Form 250 or equivalent), and must match funded amounts on the contract.",
      "Common rejection reasons: missing acceptance, CLIN mismatch, incorrect unit of measure, duplicate invoice number, or exceeding funded value.",
      "Track invoice status daily: Submitted → In Process → Accepted/Rejected → Paid. Rejected invoices stop the Prompt Payment Act clock.",
      "Under the Prompt Payment Act (31 U.S.C. 3903), the government must pay proper invoices within 30 days or owes interest — but only after valid acceptance.",
      "Troubleshoot rejections by comparing WAWF error codes to the contract's Section B funding and the COR's acceptance records.",
      "Maintain an invoice log with submission date, acceptance date, payment date, and any rejection history for audit trail purposes.",
    ],
    realSkill: "Navigate WAWF invoice submission step by step — verify CLIN funding, confirm acceptance, and resolve rejections within 24 hours.",
    exercise: {
      prompt:
        "You have three WAWF invoices pending: (1) CLIN 0001 rejected for 'No receiving report,' (2) CLIN 0003 showing 'In Process' for 12 days, (3) CLIN 0002 accepted but unpaid after 35 days. Prioritize your morning actions and draft notes for each.",
      checklist: [
        "Pull contract Section B and verify funded amounts for each CLIN",
        "Contact COR or receiving point for missing DD 250 on CLIN 0001",
        "Resubmit corrected invoice after acceptance is recorded",
        "Follow up with KO on CLIN 0003 — 12 days exceeds normal processing",
        "Calculate Prompt Payment Act interest owed on CLIN 0002 (35 days)",
        "Document all actions in the contract file invoice log",
        "Notify finance/AP of expected interest payment on overdue invoice",
      ],
    },
  },
  {
    id: "mod-request",
    time: "8:30 AM",
    title: "Review contract modification request from Program Manager",
    teachPoints: [
      "Contract modifications change scope, price, period of performance, or administrative terms — they require proper authority and documentation.",
      "Unilateral mods (SF 30) are issued by the KO alone for changes within scope under the Changes clause, option exercise, or administrative corrections.",
      "Bilateral mods require both parties' signatures — used for out-of-scope work, mutual agreement on equitable adjustments, or novations.",
      "The Changes clause (FAR 52.243-1 for fixed-price; 52.243-2 for cost-reimbursement) defines what the government may change unilaterally within the general scope.",
      "Equitable adjustments compensate the contractor for increased/decreased costs and schedule impact from directed changes — not profit on cost-type contracts.",
      "A Request for Equitable Adjustment (REA) is the contractor's formal proposal when the government directs change but has not yet issued a mod.",
      "PM requests are not contract changes — verify KO authority before performing out-of-scope work or committing company resources.",
    ],
    realSkill: "Draft a contract modification request letter with scope description, pricing rationale, and supporting cost backup.",
    exercise: {
      prompt:
        "The PM requests adding 400 hours of cybersecurity monitoring not in the PWS, citing a COR email from last week. The COR copied you but no mod was issued. Draft the internal memo and external letter you would send today.",
      checklist: [
        "Identify this as potential constructive change — work not in original scope",
        "Advise PM to stop work until KO issues bilateral mod or REA is submitted",
        "Draft REA cover letter citing FAR 52.243-1 and COR email as basis",
        "Estimate cost impact: labor hours, ODCs, schedule extension if any",
        "Attach COR email, PWS scope boundary analysis, and cost buildup",
        "Set 30-day response deadline per REA best practice",
        "Brief PM on difference between COR direction and KO authority",
      ],
    },
  },
  {
    id: "sub-consent",
    time: "9:00 AM",
    title: "Call with Contracting Officer about subcontractor consent",
    teachPoints: [
      "FAR 44.201 requires contractor consent to subcontract when the contract includes FAR 52.244-2 — common on cost-reimbursement and some fixed-price contracts.",
      "Consent is required before award of subcontracts exceeding the simplified acquisition threshold or when specifically required by the contract.",
      "The CO evaluates: subcontract type appropriatness, price reasonableness, sub responsibility, and compliance with small business subcontracting plan.",
      "Prepare a consent package: proposed subcontract, price analysis, sub's capability statement, flow-down clause list, and negotiation memo.",
      "Without consent when required, the prime bears full risk — questioned costs and potential disallowed subcontract expenses at audit.",
      "Some contracts delegate consent authority to the PCO with dollar thresholds — know your specific contract's consent requirements.",
      "Track consent requests in a log; do not authorize sub to begin work until written consent is received.",
    ],
    realSkill: "Prepare a complete consent-to-subcontract package that addresses CO review criteria on the first submission.",
    exercise: {
      prompt:
        "You need CO consent for a $1.2M FFP subcontract to a small business for cloud migration services on a cost-plus contract. Build the consent package outline and talking points for your 9:00 AM CO call.",
      checklist: [
        "Confirm FAR 52.244-2 is in the prime contract and consent threshold applies",
        "Include draft subcontract with all required flow-down clauses",
        "Prepare price analysis per FAR 15.404-3 — comparable commercial cloud rates",
        "Attach sub's SAM registration, financial capability, and past performance",
        "Document small business credit toward SF-294 reporting",
        "Prepare responses to likely CO questions on FFP sub under cost-plus prime",
        "Log consent request date and do not issue PO until consent received",
      ],
    },
  },
  {
    id: "idiq-pricing",
    time: "10:00 AM",
    title: "Proposal review — pricing the new IDIQ task order",
    teachPoints: [
      "IDIQ (Indefinite Delivery/Indefinite Quantity) contracts provide a vehicle; individual task orders define scope, price, and performance period.",
      "Ceiling price is the maximum the government will pay across all orders; funded value is what's obligated now; each task order has its own funded amount.",
      "Task order pricing must fit within labor categories, rates, and terms established in the IDIQ contract — deviations may be non-responsive.",
      "Map proposed staff to contract labor categories — mismatches cause cost realism downgrades or post-award compliance issues.",
      "Evaluate whether the task order is FFP, T&M, or cost-type — each requires different pricing structure and risk assessment.",
      "Include ODCs, subcontracts, and indirect rate application consistent with the contractor's current approved rates.",
      "Build a price matrix that cross-references PWS paragraphs to labor hours and CLIN structure for evaluator ease.",
    ],
    realSkill: "Build a task order price matrix linking PWS requirements to labor categories, hours, rates, and CLIN totals.",
    exercise: {
      prompt:
        "Price a 12-month task order under an existing IDIQ: 2 Senior Engineers (LC-003, $145/hr cap), 1 Project Manager (LC-001, $165/hr cap), 800 hours travel ODCs, and a $200K FFP sub for hardware. Fringe 28%, OH 12%, G&A 10%, fee 8%. Build the matrix.",
      checklist: [
        "Verify labor category numbers and rate ceilings against IDIQ contract Section B",
        "Calculate direct labor: hours × capped rates for each category",
        "Apply fringe, overhead, and G&A in correct order per contract terms",
        "Add ODCs and subcontract at cost (no fee on sub if contract prohibits)",
        "Apply fee only to allowable cost base per contract type",
        "Cross-reference each PWS section to hours allocated",
        "Compare total to task order funding limit and IDIQ ceiling remaining",
      ],
    },
  },
  {
    id: "sub-negotiation",
    time: "11:00 AM",
    title: "Subcontract negotiation preparation",
    teachPoints: [
      "Prime contractors flow down mandatory FAR/DFARS clauses — failure to flow down creates compliance gaps and audit findings.",
      "Fixed-price subcontracts transfer performance risk to the sub; T&M subs shift cost risk to the prime — choose based on scope certainty.",
      "Negotiate payment terms, retainage, limitation of liability, indemnification, and termination flow-down before signing.",
      "The prime must perform price/cost analysis on sub proposals per FAR 15.404-3 and document results in the contract file.",
      "Limitation of liability caps may be unenforceable on government contracts if they prevent full recovery of government damages.",
      "Include right-to-audit, EEO, small business subcontracting, and cyber (DFARS 252.204-7012) flow-downs as applicable.",
      "Document negotiation in a subcontract negotiation memo — counterpart to the government's memorandum of negotiation.",
    ],
    realSkill: "Mark up a subcontract template — identify missing flow-downs, unfavorable terms, and negotiation priorities.",
    exercise: {
      prompt:
        "Review a draft FFP subcontract from a software vendor. They deleted the termination for convenience clause, capped liability at $50K on a $800K sub, and want net-60 payment. Mark up your negotiation positions.",
      checklist: [
        "Restore FAR 52.249-2 Termination for Convenience flow-down",
        "Reject liability cap — prime remains liable to government for full amount",
        "Negotiate net-30 payment aligned with prime's WAWF payment cycle",
        "Verify DFARS 252.204-7012 and 252.204-7019 cyber clauses are included",
        "Add right-to-audit and access to records clause",
        "Confirm small business and EEO flow-downs per prime contract",
        "Prepare BATNA: alternate vendor quote for negotiation leverage",
      ],
    },
  },
  {
    id: "dcaa-followup",
    time: "1:00 PM",
    title: "DCAA auditor follow-up on incurred cost questions",
    teachPoints: [
      "DCAA audits contractor accounting systems, incurred costs, and forward pricing proposals — contractors must cooperate but protect legal rights.",
      "An audit finding is a formal deficiency; a questioned cost is a specific amount DCAA believes is unallowable — respond with evidence.",
      "Standard DCAA requests: general ledger, job cost ledger, timecards, indirect rate schedules, ICS submissions, and contract briefs.",
      "Respond professionally and on deadline — missed deadlines become presumptions against the contractor.",
      "Involve contracts, finance, and legal on significant questioned costs — responses become part of the audit record.",
      "Maintain a DCAA correspondence log with request date, due date, owner, and disposition.",
      "Understand the difference between a compliance audit (system adequacy) and an incurred cost audit (allowability of costs).",
    ],
    realSkill: "Respond to a sample DCAA information request with organized exhibits, cross-references, and a clear narrative.",
    exercise: {
      prompt:
        "DCAA questioned $47,000 in executive compensation on Contract ABC-123, citing it exceeds the benchmark. They want your response in 10 business days. Draft your response structure and identify documents to gather.",
      checklist: [
        "Pull compensation analysis supporting reasonableness per FAR 31.205-6",
        "Gather board minutes, compensation survey data, and employment agreements",
        "Trace charges to ABC-123 job cost ledger — verify proper allocation",
        "Coordinate with HR and legal before submitting",
        "Draft cover letter addressing each questioned item by reference number",
        "Include executive's role on the contract and hours charged",
        "Log response in DCAA tracker and calendar follow-up date",
      ],
    },
  },
  {
    id: "status-report",
    time: "2:00 PM",
    title: "Monthly contract status report for program review",
    teachPoints: [
      "Monthly status reports communicate funding burn rate, schedule, risks, and EAC to internal leadership and sometimes the customer.",
      "Track funded value, cumulative costs, percent complete, and remaining funding — flag when burn rate exceeds plan.",
      "Estimate at Completion (EAC) = actual costs to date + Estimate to Complete (ETC); compare to total funded value.",
      "Earned Value metrics: BCWS (planned value), BCWP (earned value), ACWP (actual cost); CPI = BCWP/ACWP, SPI = BCWP/BCWS.",
      "Report cost overruns early — waiting until funding exhaustion triggers Limitation of Funds notices and damages credibility.",
      "Include subcontractor status, open mods/REAs, compliance issues, and staffing changes.",
      "Use consistent formats so leadership can compare across the portfolio.",
    ],
    realSkill: "Complete a contract status report template with accurate EAC, variance analysis, and recommended actions.",
    exercise: {
      prompt:
        "Month 8 of 12: Funded $2.4M, spent $2.1M, BCWP $1.85M, BCWS $2.0M. Subcontractor is 3 weeks behind. Draft the status report narrative and flag the appropriate concern level.",
      checklist: [
        "Calculate CPI (0.88) and SPI (0.925) — both below 1.0 indicate problems",
        "Compute EAC: if current trend continues, project total cost at completion",
        "Flag cost overrun risk — 87.5% funding consumed at 67% schedule",
        "Document subcontractor delay impact on milestone MS-003",
        "Recommend corrective actions: recovery plan, LOF notification if needed",
        "Include open REA status and any pending mods",
        "Brief PM on talking points before program review meeting",
      ],
    },
  },
  {
    id: "kickoff-prep",
    time: "4:00 PM",
    title: "New contract award — kickoff meeting preparation",
    teachPoints: [
      "Contract kickoff meetings align the team on scope, deliverables, key personnel, reporting, and administration procedures.",
      "Attendees: PM, COR, KO (sometimes), contracts, finance, quality, security, and key subcontractors as appropriate.",
      "First read of the contract: Section B (pricing/funding), Section C (PWS/SOW), Section E/F (admin/inspection), Section I (clauses), Section J (attachments).",
      "First 30 days: establish contract file, load CLINs into accounting, brief team on security/export requirements, and schedule sub kickoffs.",
      "Identify high-risk clauses immediately: security, data rights, OCI, small business limitations, and option provisions.",
      "Prepare kickoff slides: contract overview, org chart, milestone schedule, communication plan, and open questions for the COR.",
      "Document kickoff decisions and action items — they become part of the contract administration record.",
    ],
    realSkill: "Build a contract kickoff checklist and agenda covering all functional disciplines within the first week of award.",
    exercise: {
      prompt:
        "You received award of a $4.5M cost-plus IT services contract with classified elements, 5 option years, and a small business subcontracting plan. Build the kickoff agenda and first-30-days checklist.",
      checklist: [
        "Schedule kickoff within 5 business days of award — invite KO, COR, PM, subs",
        "Prepare contract summary: CLINs, POP, key clauses, security level",
        "Assign contract file custodian and set up electronic file per FAR 4.802",
        "Brief security on DD 254 requirements and facility clearance needs",
        "Load contract into accounting/ERP with correct contract type and rates",
        "Issue internal flow-down memo listing mandatory clause compliance actions",
        "Schedule subcontractor kickoffs within 10 days — verify flow-down matrix",
        "Draft SF-294 small business reporting calendar for the team",
      ],
    },
  },
];
